apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mbesancon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mbesancon
    spec:
      containers:
      - name: api
        image: mbesancon/hotpot:latest
        ports:
        - name: api
          containerPort: 8080
