package detector

import (
	"github.com/chrisport/go-lang-detector/langdet"
)

func init() {
	for language, text := range languagesTrainer {
		detector.AddLanguageFromText(text, language)
	}
}

// GuessLanguage returns the detected language for the
func GuessLanguage(text string) string {
	return detector.GetClosestLanguage(text)
}

var (
	detector         = langdet.NewDetector()
	languagesTrainer = map[string]string{
		"french": `
		Etonnement de he poussaient gouverneur de avancaient sa compagnies. Le tire de hein mais hate voix tuer. Relevent treillis nul les remporte ici mon. Succedent moi ici eux toutefois peu dernieres echangent messieurs. Peu les maintenant ans des republique electrique vieillards gourmettes ordonnance. Bon hauts aux fer eut chose monte. Sur comprendre sol fer atteignait construits instrument tricolores. Etoffes express galoper enfants le paysans oh.
		Joyeuses depenser en trouvait en ah et. Simple il pentes revele ah reunir on. Et persuada dressait batterie ma as or. Oh trouvent la un aussitot jeunesse. Nez flaques retreci peu accable encourt parlait epaules moi. Souffle entiere capotes oh ne lisiere ah je. Reve dont aux fer unir. On triste chiens delire revele quelle sa. Bougres as ciments secouee fatigue on tu voulons.
		Acier poids joies force bas toi mal hauts croix des. Confie livree guerre eperon je regard tomber le en. On quelques la il debouche adjudant ah. Rit raison peu grille vallee par sur. Plates douane bouche metres fit contes nid fondit ras ils. On repousser dentelees illumines et pu suffisait.
		Ah rappelles apprenons incapable courroies perruches ma. Arrivons treillis chercher etranges trahison sur ils essaiera toi. Si voyons chants contre xv. Sa la enfin on matin vingt en heros. Iii noms fort sur elue. Entremise cesserent inassouvi la ce. Admiration comprendre toi une clairieres ere uns cimetieres.
		Chez on prit et on deux. Sous mene ici uns tout cet bon. Prenaient me consumait tiendrons ai parlaient connaitre frontiere. Poussiere indicible cuirasses agreerait cartouche des comprends que toi. Donc saut va idee et vive. Avantage epandent cavalier mon toi sol. Coeur repit et homme large luire voeux xv. Reparler toi charrues oui non lumieres des pressait. Ne sa resterait ah meconnais fabriquer oh. Hors robe car cite joue tete aux eut ame pere.
		Repartit peu fer mes ennemies viennent par. Boules ils livree mirent toi non routes mal. Executeurs au defilaient le un subitement lumineuses. Progres art qui douleur dansent courtes ton. Va militaire consumait alternent souvenirs oh arrachait. Jet douze peu foret verte halte savez dut. Ici infanterie nationales tricolores ils bouquetins permission. Eut ici flaques nations fleurir empeche les malheur. Cent peu pres sons moi cree. Feeriques polygones ah suspendue enfantent il qu prenaient.
		Ras adorer touffe beaute peu ans. Ont trouve aux les ifs parees gronde. Faite armes nul garde sur elles court. Caractere oui viendrait vin accoudees tot certitude. Est ont aux vieillards patiemment republique bouquetins estaminets. Cassait oh dragons ce abattre me. Blancs vin soeurs autres non menent paquet gronde. Et joue seul tu plus. Je la donc veut avez on quoi.
		Pic pas gardent eux nez semence seconde. Reciter ras des mes par tristes carreau fausser portent ennemie. Primeveres en approchait habilement convulsion il eu infanterie admiration te. La taches oh bondir sabres. Magistrats eux car petitement les chantaient ici atteignait tristement asiatiques. Ils droit desir sol gifle. La furent du eclate claire ne suivit diable troupe la. Aimons wagons femmes ah je on hordes nuages ah.
		Surement prudence ne interdit oh et oh. Pierre et orient reelle on flancs te. La comptait quarante continue la sa on. Et prennent ah qu donnerai longeait. Pas recrues diables car pourrai attenua puisque petites ces. Laissez elancer prepare si je conseil qu va. Nous tres cet ici paix. Et aimons petite ruches tenter charge un. Initiez ah entendu elancer accable sa au vieille.
		Terrasse et ai etrangle te bataille dissiper musiques bravoure. Continue preparer pressait que etroites empecher habitent oui. Vit ere infiniment descendons simplement eux. Les malheur publics pic epouser vif. Jeu pois son avis mene tard pile bien. Illumine harmonie le oh entendit de. Eclaireurs au historique rougeatres va petitement frisottent. Capucines effrayant au me en et epaissies existence alternent descendit.
		`,
		"english": `Style never met and those among great. At no or september sportsmen he perfectly happiness attending. Depending listening delivered off new she procuring satisfied sex existence. Person plenty answer to exeter it if. Law use assistance especially resolution cultivated did out sentiments unsatiable. Way necessary had intention happiness but september delighted his curiosity. Furniture furnished or on strangers neglected remainder engrossed.
		Placing assured be if removed it besides on. Far shed each high read are men over day. Afraid we praise lively he suffer family estate is. Ample order up in of in ready. Timed blind had now those ought set often which. Or snug dull he show more true wish. No at many deny away miss evil. On in so indeed spirit an mother. Amounted old strictly but marianne admitted. People former is remove remain as.
	Letter wooded direct two men indeed income sister. Impression up admiration he by partiality is. Instantly immediate his saw one day perceived. Old blushes respect but offices hearted minutes effects. Written parties winding oh as in without on started. Residence gentleman yet preserved few convinced. Coming regret simple longer little am sister on. Do danger in to adieus ladies houses oh eldest. Gone pure late gay ham. They sigh were not find are rent.
	Sportsman delighted improving dashwoods gay instantly happiness six. Ham now amounted absolute not mistaken way pleasant whatever. At an these still no dried folly stood thing. Rapid it on hours hills it seven years. If polite he active county in spirit an. Mrs ham intention promotion engrossed assurance defective. Confined so graceful building opinions whatever trifling in. Insisted out differed ham man endeavor expenses. At on he total their he songs. Related compact effects is on settled do.
	Passage its ten led hearted removal cordial. Preference any astonished unreserved mrs. Prosperous understood middletons in conviction an uncommonly do. Supposing so be resolving breakfast am or perfectly. Is drew am hill from mr. Valley by oh twenty direct me so. Departure defective arranging rapturous did believing him all had supported. Family months lasted simple set nature vulgar him. Picture for attempt joy excited ten carried manners talking how. Suspicion neglected he resolving agreement perceived at an.
	Behaviour we improving at something to. Evil true high lady roof men had open. To projection considered it precaution an melancholy or. Wound young you thing worse along being ham. Dissimilar of favourable solicitude if sympathize middletons at. Forfeited up if disposing perfectly in an eagerness perceived necessary. Belonging sir curiosity discovery extremity yet forfeited prevailed own off. Travelling by introduced of mr terminated. Knew as miss my high hope quit. In curiosity shameless dependent knowledge up.
	Lose eyes get fat shew. Winter can indeed letter oppose way change tended now. So is improve my charmed picture exposed adapted demands. Received had end produced prepared diverted strictly off man branched. Known ye money so large decay voice there to. Preserved be mr cordially incommode as an. He doors quick child an point at. Had share vexed front least style off why him.
	Increasing impression interested expression he my at. Respect invited request charmed me warrant to. Expect no pretty as do though so genius afraid cousin. Girl when of ye snug poor draw. Mistake totally of in chiefly. Justice visitor him entered for. Continue delicate as unlocked entirely mr relation diverted in. Known not end fully being style house. An whom down kept lain name so at easy.
	An country demesne message it. Bachelor domestic extended doubtful as concerns at. Morning prudent removal an letters by. On could my in order never it. Or excited certain sixteen it to parties colonel. Depending conveying direction has led immediate. Law gate her well bed life feet seen rent. On nature or no except it sussex.
	Gay one the what walk then she. Demesne mention promise you justice arrived way. Or increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye an. Mr unsatiable at literature connection favourable. We neglected mr perfectly continual dependent.
		`,
		"german": `Gott wand sind dich wo alte ja ware. Als gru sto ernstlich schnellen viehmarkt. Tur bette kalte statt reist das drein hab das. Frohlich aufstand doppelte pa wo. Vorstadt fraulein so freundes getraumt zu. Uhr laufen hinten mussen hat reihen konnte bitter. Gegenteil gescheite den ans zerfasert flu art ausgeruht flanierte arbeitete. Bi satz er um sieh drin habs. Em zahne du blick ab lagen recht regen.
Vielleicht sei mancherlei bilderbuch arbeitsame her grasgarten. Heimweh fischen da bi niedere. Flo ihr ihnen hielt tod anzug weile. Euch tor ganz wei lang bist. Ige was ist hergab daumen ruhten. Wu langen ab er am vielen spital herrje willen frauen. Fu wuste ganze meine getan moget um en stand. Herum hatte te deine herrn wenig am. Dem frohlich erschien schonste sto hob gewartet jenseits. Auf angst gut wie drang dampf schon auf.
Ich sagen genie macht klare augen tag. Darin stube mu da litze zu indes wu. Pa he gepfiffen hochstens dunkelrot kammertur. Man nur gefallt die frieden erstieg dunklem gut. Schuchtern da dienstmagd bangigkeit pa he ja freundlich. Schuftet en doppelte em brauchst schweren am eigentum gespielt. Hab sei zog hubsche manchen schurze besorgt obenhin bosheit ach. Mir stockwerk schwemmen her des kraftiger zur. Hatt wu eben er ging du bart hell du.
Nur weibern speisen schaute frieden brachte bat. Mehrere stiefel gelegen lag tod oha traurig die. Weil sa se sein ward darf. In brotlose an unbeirrt du behutsam schlafen heiraten funkelte. Aussah all bis solche sitzen gro volles fallen. Halblaut erzahlte wu zu funkelte gefunden eleonora gefallts um. Mi sauber drehte la schlug. Was sag lustig des unterm madele zeigen ich diesem. Ja sprach gehabt wirtin werden wo bi ja. Alten uns kam kerze zur kinde das herrn leise.
Bi wo ubrigen standen bosheit flecken. Im aufzulosen augenblick da nachtessen nachmittag dienstmagd schuchtern. Stie mein ihr aus ein gelt euch. Gewu sies ware mi darf ab wert. Knopf sa du te sogar he statt. Macht aller herrn ein hause riefe ich. Heut aber ichs man bist wer ganz.
Hier so sich zu dort. Marktplatz befangenen neidgefuhl tut ins ige sei. Wo ja he ihre satz kund. Um zu regungslos dammerigen todesfalle aufzulosen ob im ungerechte aufmerksam. Bin hof spazieren bedeckten vom nichtstun neugierig vogelnest. Em hinabsah funkelte neunzehn brauchen talseite so gespielt. Denkt muhle ja er einer da fu indem. Stockwerk wei lohgruben ach furchtete schleiche. Uber auch sage hatt da du steg magd.
Eben ware ehe fur mein flie meer. Ubelnehmen achthausen kartoffeln bescheiden em dachkammer er. Je ehre bild so tage. Spruche bestand filzhut ort wachter antwort gab fur gefallt. Dreien sauber winter um gassen mi grunen la ja. Jede lauf em warf neue se. Freund siehst stelle fragte so spinat im du herauf. Nie morgen denken rothfu halten tut bis ungern.
Ist sah unsicherer ach lag geschwatzt wasserkrug. Gelernt solchen heiland lichten ob glatten schlief mu. Dazwischen tat messingnen eigentlich ordentlich leuchtturm hof vor vorpfeifen vor. Jemals je dessen allein gesagt sterne bi darauf. Ruh trillern behutsam blaulich ton geworden erkannte hin was. Gegessen launisch man abraumen vergnugt wirklich getrennt ehe sog geh.
Haften handen baumen wisset ja em da. Ins ein ige sogar weste wesen. Duse da ging neue da. Bett um hier darf eine oden te ward. Begleitete arbeitsame tat geschwatzt ist todesfalle ins. Gelernt wu schritt bosheit pa da dunklen wo. Rabatten ku lauschte tadellos entgegen zugvogel es es erzahlen. Trillern nur bis zinnerne auf befehlen schonste. Bibel sei angst tal ihr nun gehen. En se bilderbuch bugeleisen dachkammer ku ei.
Bist kaum was all berg scho laut man. Kam ziel wir gru noch lie gelt. Mitwisser anzeichen flanierte dunkelrot gepfiffen nie flu und uhr barbieren. Ich was des auf ding berg oden herd lieb. Te sudwesten hauswesen gescheite im neugierde. Fruh hier rand auf ehe dann gast wenn.`,
	}
)
